- hosts: terraform-ansible
  tasks:
    - name: "Intall python3 and virtualenv"
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: "Installing dependencies with pip (Django and Dajngo Rest)"
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
